[versions]
kotlin = "2.2.0"
compose = "1.8.0"
compose-hot-reload = "1.0.0-alpha10"
storyboard = "0.1.0-alpha03"
haze = "1.5.2"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }

[libraries]
storyboard = { module = "dev.bnorm.storyboard:storyboard", version.ref = "storyboard" }
storyboard-easel = { module = "dev.bnorm.storyboard:storyboard-easel", version.ref = "storyboard" }
storyboard-text = { module = "dev.bnorm.storyboard:storyboard-text", version.ref = "storyboard" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }